name: built_collection_value_practice
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Naoto Higuchi <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.0.4
  built_collection: ^4.0.0
  built_value: ^6.0.0
  
dev_dependencies:
  build_runner: '>=0.9.0 <0.11.0'
  built_value_generator: ^6.1.4  
  test: ^1.0.0
  